export const GET_DATA_DETAILS_REQUEST = "GET_DATA_DETAILS_REQUEST";
export const GET_DATA_DETAILS_SUCCESS = "GET_DATA_DETAILS_SUCCESS";
export const GET_DATA_DETAILS_FAILURE = "GET_DATA_DETAILS_FAILURE";
